
SOURCE_FILES="appt.c \
        cal.c \
        curses_ui.c \
        enter.c \
        getline.c \
        log.c \
        main.c \
        settings.c \
        strutils.c"

GENERATED_HEADERS="config.h"

